includes:
  - https://github.ibm.com/cloud-docs/overview
  - https://github.ibm.com/cloud-docs/icons
  - https://github.ibm.com/cloud-docs-solutions/deployable-reference-architectures
  - https://github.ibm.com/cloud-docs/bare-metal
  - https://github.ibm.com/cloud-docs/virtual-servers